### ISSUE TITLE
Firehose dies during a Loadbalancer failover

### ISSUE THREAD

**Issue by janaurka** [cloudfoundry-community/firehose_exporter#15] opened 2017-05-17 14:35 UTC
Hey *

Apparently `firehose_exporter` silently dies when there is a LoadBalancer failover.

We did a LoadBalancer failover test (using F5 BigIP) and instantly all our `firehose_exporter` died silently (all of them, there are 4 or 5 running on various systems).

-> The F5 is in front of the `go-router` which will be used to get to the `doppler`.

What happened:

The MAC Address of the LoadBalancer changed, the VIP stayed the same and the ARP change was properly announced. 

The processes were still reported as running by `monit`. We’ve restarted all of them without debugging any further (sorry :) ).

It would be cool if 

1. The `process` would simply die if something like this happens and `monit` will then restart it.
2. The `firehose_exporter` is able to survive the failover.

cheers

**Comment by frodenas** [comment] 2017-05-17 19:02
@janaurka Would love to see the logs. In case the exporter loses the firehose connection, it will try to reconnect automatically using a back-off strategy (provided by the official [noaa consumer](https://github.com/cloudfoundry/noaa) library). So theoretically it should *survive* any network glitch (or a LB failover). Maybe there was a weird scenario here at the noaa library was unable to reconnect, but without the logs is quite difficult to diagnosticate.

w/r/t the process not dying, that's by design. Depending on the error (ie: `doppler` closing the stream), the process dies (and `monit` will try to restart it). But if `noaa` returns a `retryable` error then the process continues (as it will try to reconnect). For the latter scenario, the exporter will return the last time an envelope was received, and there's an [alert](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/src/cloudfoundry_alerts/prometheus_firehose_exporter.alerts#L13) that will be triggered if is older than 10 mins ago.

**Comment by janaurka** [comment] 2017-05-19 11:02
Hey @frodenas 

There is basically nothing in the logs around the failover happening :(

Is it possible that there is a `max retry` setting or so, when it catches a `retryable`?

We had some problems during the failover which ended up in `doppler` not being reachable for some time.


Yeah, the alert (and the missing entries in the `logsearch` deployment) led us to this.

cheers
j

**Comment by geofffranks** [comment] 2017-06-01 13:38
May have encountered a similar issue last night. Nothing in the cf_exporter logs, but when I hop on the box, I see:

```root     10045     1  0 May25 ?        01:34:03 firehose_exporter -uaa.url=https://uaa.system.prod.cf.demandbridge.io -uaa.client-id=firehose -uaa.client-secret=wBtJvibvRXAfnn4dqSD5xX2F1JSsq5gsJTuRm6uGw76vHJiN6PZjZmdyrS9bdhxU -doppler.url=wss://doppler.system.prod.cf.demandbridge.io:443 -metrics.environment=db-eastus-prod -skip-ssl-verify=true -web.listen-address=:9186
root     10048 10045  0 May25 ?        00:00:00 [firehose_export] <defunct>
root     10049 10045  0 May25 ?        00:00:00 [firehose_export] <defunct>```

There's an established TCP connection to loggregator that's receiving traffic, but it's currently owned by 10045. Seems like the firehose_exporter child processes crashed, and the parent never noticed/cleaned them up?

**Comment by geofffranks** [comment] 2017-06-01 13:47
At roughly the same time as the firehose_exporter stopped, i see the following errors in my firehose2syslog process (for logsearch):

```
[2017-05-24 21:30:30.8954517 +0000 UTC] Exception occurred! Message: Error while reading from the firehose Details: websocket: close 1006 (abnormal closure): unexpected EOF
[2017-05-24 21:30:30.8954892 +0000 UTC] Exception occurred! Message: Closing connection with traffic controller due to error Details: websocket: close 1006 (abnormal closure): unexpected EOF
[2017-05-24 21:30:30.8955508 +0000 UTC] Exception occurred! Message: Failed connecting to Firehose...Please check settings and try again! Details:
2017/05/24 21:30:35 New Client: Could not get api /v2/info: Get https://api.system.prod.cf/v2/info: dial tcp 10.0.51.4:443: getsockopt: connection refused
```

**Comment by frodenas** [comment] 2017-06-04 16:18
@janaurka @geofffranks I've been doing several tests, but I was unable to reproduce this. Every time I restart one of the loggregators, or I temporarily disable access from the exporter to doppler, the exporter is reconnecting again.

So I'm completely blind here. I suspect (and it's just a theory), that the consumer wss connection is somewhat closed, and the retry action is then doing nothing. The retry is infinite, so I guess it was just in a dead loop without detection any error, but again, it's just a theory.

I've upgraded the [noaa consumer](https://github.com/cloudfoundry/noaa) library to the latest version, as it allows now to specify a max retries (by default, `1000` times). I've added a new flag to the exporter (`doppler.max-retry-count`) to allow override this default. Hopefully, it will stop the loop after the max retries, aborting the exporter (so `monit` will restart it again). So please upgrade the exporter to [v4.2.0](https://github.com/cloudfoundry-community/firehose_exporter/releases/tag/v4.2.0) (it's shipped at the prometheus bosh release [v17.2.0](https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v17.2.0)).

I'll keep this issue open some more weeks in case anyone reproduces it again with the new exporter version.

**Comment by frodenas** [comment] 2017-06-21 20:08
I'm closing this, we can reopen it if the problem still persists when using the new version.

**Closed by frodenas** 2017-06-21 20:08 UTC
Labels: bug

**Comment by geofffranks** [comment] 2017-06-21 20:22
Yeah, I was running on v14.0.0 of prometheus-boshrelease, so it's entirely possible that the issue was fixed long ago. In the process of upgrading to 17.4.x, will re-open if i see this again.
